// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42Ak6laSUghhfVg11OLCiBDF9XYu7rmc',
    appId: '1:1020462632114:android:13fcb38c7646188054cdab',
    messagingSenderId: '1020462632114',
    projectId: 'attendance-eb70e',
    databaseURL: 'https://attendance-eb70e-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-eb70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIi4zBtJ34w-nD3dcxX1C5Cx8fiILvfm4',
    appId: '1:1020462632114:ios:3ad06c418a3fd85554cdab',
    messagingSenderId: '1020462632114',
    projectId: 'attendance-eb70e',
    databaseURL: 'https://attendance-eb70e-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-eb70e.appspot.com',
    iosClientId: '1020462632114-oipipa53m3rt54echf6gvn245vtjb4su.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
